---
title: Contributions in "An open IoT platform for the management and analysis of energy
  data"
output:
  pdf_document: default
  html_document: default
---

I agree that the Ph.D student Aurora Gonz치lez Vidal includes the journal paper "An open IoT platform for the management and analysis of energy data" that she co-authores with me as part of her compendium thesis and I commit to not using such paper as part of another Ph.D thesis.

I confirm that the sections of the paper where Aurora Gonz치lez Vidal has strongly contributed are:

- 3.2.2 Homogenization and storage layer: addressing the heterogeneity of the incoming energy-related data and data cleaning processes.
- 3.2.3 Analytics support layer: representation of HVAC devices in a time series manner based on their usage and the aplication of specific clustering methods in order to group rooms depending on that.
- 3.2.4. The service layer where it is explained that results have been shown in a graphical manner.
- 4.2. Pilot objectives: description of the actions that are included in the IoT Energy Platform (IoTEP) application. The energy consumption prediction service was also integrated and the comparisons of results between the models generated by different inputs is presented in this section.

In the rest of the sections, Aurora has contributed in approximately the following numbers:

- 1. Introduction: 20%
- 2. Related work: 40 %
- 4.3. Lessons learnt: 40 %




\vspace{40 mm}
Fdo: Fernando Terroso S치enz \hspace{10 mm}  Fdo: Alfonso P. Ramallo Gonz치lez \hspace{10 mm}  Fdo: Antonio F. Skarmeta
<div style="width:200px"><hr/></div>
\noindent\rule{4.75cm}{0.4pt} \hspace{8 mm} \noindent\rule{5.5cm}{0.4pt}\hspace{9 mm} \noindent\rule{4.5cm}{0.4pt}

